'use strict';
require('dotenv').config();
const express = require('express');
const cookieSession = require('cookie-session');
const path = require('path');
const { requireAuth } = require('./middleware/auth');
const authRoutes = require('./routes/auth');
const apiRoutes  = require('./routes/api');
const REQUIRED = ['SESSION_SECRET','APP_USER','APP_PASSWORD','ANTHROPIC_API_KEY'];
const missing  = REQUIRED.filter(k => !process.env[k]);
if (missing.length) { console.error('[PEDRI] Missing env vars:', missing.join(', ')); process.exit(1); }
const app  = express();
const PORT = parseInt(process.env.PORT || '3001', 10);
app.set('trust proxy', 1);
app.use(express.json({ limit: '2mb' }));
app.use(express.urlencoded({ extended: true }));
app.use(cookieSession({ name: 'pedri_sess', secret: process.env.SESSION_SECRET, maxAge: 8*60*60*1000, httpOnly: true, secure: false, sameSite: 'lax' }));
app.use((req, res, next) => { res.setHeader('X-Content-Type-Options','nosniff'); res.setHeader('X-Frame-Options','DENY'); res.setHeader('Referrer-Policy','strict-origin-when-cross-origin'); next(); });
app.use((req, res, next) => { const t = Date.now(); res.on('finish', () => console.log(`[${new Date().toISOString()}] ${req.method} ${req.path} ${res.statusCode} ${Date.now()-t}ms`)); next(); });
app.get('/health', (_req, res) => res.json({ status: 'ok', app: 'pedri', uptime: Math.floor(process.uptime()) }));
app.use('/auth', authRoutes);
app.get('/login', (req, res) => { if (req.session && req.session.authenticated) return res.redirect('/'); res.sendFile(path.join(__dirname, 'public', 'login.html')); });
app.use(requireAuth);
app.use(express.static(path.join(__dirname, 'public')));
app.use('/api', apiRoutes);
app.get('/', (_req, res) => res.sendFile(path.join(__dirname, 'public', 'index.html')));
app.use((_req, res) => res.status(404).json({ error: 'No encontrado' }));
app.use((err, _req, res, _next) => { console.error('[ERROR]', err.message); res.status(500).json({ error: 'Error interno' }); });
app.listen(PORT, '0.0.0.0', () => { console.log('[PEDRI] Running on port', PORT); console.log('[PEDRI] NODE_ENV:', process.env.NODE_ENV || 'development'); });
